# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=webapp.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('IGN', models.CharField(max_length=140)),
                ('country', models.CharField(choices=[('DENMARK', 'DENMARK'), ('FINLAND', 'FINLAND'), ('FRANCE', 'FRANCE'), ('GERMANY', 'GERMANY'), ('ITALY', 'ITALY'), ('NETHERLADNS', 'NETHERLANDS'), ('NORWAY', 'NORWAY'), ('RUSSIA', 'RUSSIA'), ('SPAIN', 'SPAIN'), ('SWEDEN', 'SWEDEN'), ('U.K.', 'U.K.'), ('CANADA', 'CANADA'), ('MEXICO', 'MEXICO'), ('U.S.', 'U.S.'), ('BRAZIL', 'BRAZIL'), ('AUSTRALIA', 'AUSTRALIA'), ('ARABIC', 'ARABIC')], max_length=20)),
                ('guide', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
